### ISSUE TITLE
Couple questions

### ISSUE THREAD

**Issue by zcohen-nerd** [printermods/xchange#1]
I received my XChange today and have been playing with it a bit. Haven't mounted anything yet since I'm still figuring out how I'm going to do everything. A few things have come up though that I wanted to ask/bring up for others.

- The installation guide video needs some work. The sound is pretty bad and sometimes its hard to see whats actually being done. I dont expect it any time soon, but I feel videos in general just aren't the best way to show how to assemble something. I found the [Inventables X-Carve instructions](https://x-carve-instructions.inventables.com/1000mm/) to be extremely well done. Something like that would be really helpful.
- It would be helpful to see installations on multiple printers and not just a CoreXY. Specifically seeing the setup on a bed slinger would be really helpful since I feel like a lot of people have that style of printer.
- In the video you mentioned a 3D printable tool to install the alignment pins. Do you have a link to that?
- It would be nice to have pictures of the various mounts that you have as STLs on GitHub. I've been looking at figuring out how to mount the Petsfang system I use for everything and saw the ender stock fan shroud adapter. I think that works, but when I loaded it into CAD with the plate I couldn't quite figure out how it was mounted exactly. Having a picture of it mounted to a tool plate for that and any other mods would be super helpful.
- You had mentioned it in an email, but we really need a community to discuss with each other. Anything, be it Slack, Discord, Facebook, whatever. It would be nice to ask others who are using this system and not be out there on my own figuring it out. Also as I figure things out I want to contribute, but dont really know where to do so yet.
- For the actual XChange, everything seems well made/machined except for the anodization. I ordered five tool plates and a master assembly and all of them came out of the bag with scratches. Personally I don't care and am not looking for anything to fix it for me, but it doesn't look great receiving something with scratches.
- The packaging overall was simple but does there have to be so many bags? I'm throwing out a ton of single use plastic bags and its kind of depressing. I dont think every type of part needs its own bag. Or if there does need to be separation, at least a more environmentally friendly way would be nice.

Thanks overall for a pretty awesome looking product. I'm looking forward to installing it!

**Comment by zcohen-nerd** [comment]
Sorry, one more question. What is the purpose of the auxiliary docking pads on the tool plate side?

**Comment by scepterr** [comment]
There's a Facebook group available, https://www.facebook.com/groups/549481366050754

**Comment by printermods** [comment]
@zcohenld Great questions / feedback, thank you. See our replies in order:

- We are definitely creating a web-based and PDF guide for installation! The video was really intended to be a band-aid for the near term, and we apologize that the quality isn't up to snuff. Future videos will be much better.
- The Ender-5 was chosen as kind of a middle-ground machine, but we plan to do publish our instructions for an Ender-3 V2 machine, which should be a little more universal (and simpler).
- That alignment pin tool will be published today in the Printable Files section.
- As @scepterr mentioned, the Facebook group is the one we've landed on right now based on user feedback. We'll also try to be responsive to comments and issues here as well.
- Would you send us photos of the anodization issue you had? We'd like to see if the scratches you're referring to occurred post-anodization, as we had a batch from our anodize partner packaged a bit haphazardly and that's a possibility. If you'd be so kind, please send them to us at support@printermods.com and reference this conversation.
- You're absolutely right about the packaging. We planned on having custom-cut foam inserts ready by now, but worldwide PU foam shortages have necessitated that we put that plan on hold. We're working on a solution that will be more environmentally friendly, easier to unpackage, and easier for us to package as well.

Thanks for taking the time to give your feedback!

**Comment by printermods** [comment]
> Sorry, one more question. What is the purpose of the auxiliary docking pads on the tool plate side?

Sorry we missed this. The auxiliary docking pads on the tool boards are for a secondary, powered "stand by" dock that we will be releasing plans and kits for. It will include auxiliary connections for powering the heater, hot end cooling fan and thermistor for each tool, with the intention of bringing that tool to (and sustaining) a desired temperature while not connected to the master assembly.

**Comment by zcohen-nerd** [comment]
That's so extremely cool and such an awesome idea. Thank you for sharing! I'm really excited to see that!
