### ISSUE TITLE
Auto bed leveling connector

### ISSUE THREAD

**Issue by RJSavell** [printermods/xchange#11]
It does not appear that pin 4 on the auto bed leveling connector is connected to the ground (or pin1) as shown in the schematics.   Is this pin not needed for the BL Touch / CR Touch or are we supposed to solder a wire between these pins?

**Comment by zchrykng** [comment]
I just went through a checked the connections with a multi-meter. One of the pins is actually completely dead. I’d just go through and check it personally. Two of the pins are connected to a common ground, so make sure you don’t hook your 5v to one of those for instance.

**Comment by RJSavell** [comment]
I have checked every pin on P2 and P2 pin 6 is marked a NC so that is expected but P2 pin 4 should go to P1 pin 9 (ground) but it is not  connected to anything, I checked all of the possible connection.   This is the same on the 3 tool plate PCBs and the master PCB.  I have a friend who bought this at the same time as I did and he has the same problem.

**Comment by zchrykng** [comment]
Take a look at the image in this pull request. The pins are labeled. https://github.com/printermods/xchange/pull/7/files

The pins are arranged like the below if you are looking at them straight on.

```
4 5 6
1 2 3
```

4 and 1 are common grounds. 6 is dead.

**Comment by RJSavell** [comment]
Zachary,

Unfortunately the traces on the PCB do not match the schematic.  There is no connectivity between P2 Pin 4 and any other pin on the PCB

Thanks!

**Comment by zchrykng** [comment]
Maybe you got a bad unit then. I’ve verified that what I said is the case on what I have.

**Comment by RJSavell** [comment]
as it turns out I had pins 4 and 6 reversed - while I swore I had tested every combination apparently I has not :-(
Thanks for everyone help!!!
