### ISSUE TITLE
stock fans

### ISSUE THREAD

**Issue by bakaneko718** [printermods/xchange#2]
i see there is a file here for stock fan shroud, but i cant download it to check it out and see how it will work for me. there are a few of the files that are not available to download actually. 

somewhat related is there a scale diagram for the tool plate?

**Comment by printermods** [comment]
Thank you for bringing this to our attention.

To the best of our reckoning, it's a GitHub issue, and we've created a ticket and asked for their help.

We will leave this issue open until it's resolved. In the meantime, two options:  you can either download the raw data and save it to a notepad file (rename it X.STL), or you can download the entire repository from the home directory.

Sorry for the inconvenience.

**Comment by printermods** [comment]
@bakaneko718 oops, turned out to be an export / encoding issue with the file upon closer inspection. It's corrected now. Thanks!
