### ISSUE TITLE
Hole pattern diagram for the XChange Tool Plate

### ISSUE THREAD

**Issue by C0unt23r0** [printermods/xchange#6]
I've seen a description for each hole on your homepage for the MDD tool plate but not for the XChange. 
Link: https://cdn.shopify.com/s/files/1/0054/6311/3799/products/MDD-V1.3-ENDER-3-CR-10-DIRECT-DRIVE-HOLE-PATTERN-DIAGRAM_a29303f0-6256-46aa-8563-0ae83a8569ad_495x495.png?v=1600700521

Would be nice to see for what all these holes are meant for. I hope I didn't missed anything.

**Comment by printermods** [comment]
Closing this as the requested diagram was later posted to Kickstarter and is now available in the repository: https://github.com/printermods/xchange/blob/main/XChange-v1-tool-plate-diagram.jpg
